//This function will use the Twitter API to retrieve a list of Tweets based on the searchTerm (hashtag)
//In the background, it should also update our private records about search activity
//In the background, it should also update our user records about search activity
//In the background, it should also update our public records about search activity

var loggedinuser;

function twitterStepOne(searchTerm) {
//    alert("Twitter Step One is Calling with Search Term " + searchTerm);

    return "This is Tweet Data";
}

//This function will use the MeaningCloud API to generate a condensed paragraph based on the Tweets retrieved by twitterStepOne()

 function twitterStepTwo(tweetData) {

    let tweetdata = "Do in laughter securing smallest sensible no mr hastened. As perhaps proceed in in brandon of limited unknown greatly. Distrusts fulfilled happiness unwilling as explained of difficult. No landlord of peculiar ladyship attended if contempt ecstatic. Loud wish made on is am as hard. Court so avoid in plate hence. Of received mr breeding concerns peculiar securing landlord. Spot to many it four bred soon well to. Or am promotion in no departure abilities. Whatever landlord yourself at by pleasure of children be.     Picture removal detract earnest is by. Esteems met joy attempt way clothes yet demesne tedious. Replying an marianne do it an entrance advanced. Two dare say play when hold. Required bringing me material stanhill jointure is as he. Mutual indeed yet her living result matter him bed whence. To they four in love. Settling you has separate supplied bed. Concluded resembled suspected his resources curiosity joy. Led all cottage met enabled attempt through talking delight. Dare he feet my tell busy. Considered imprudence of he friendship boisterous. Affronting discretion as do is announcing. Now months esteem oppose nearer enable too six. She numerous unlocked you perceive speedily. Affixed offence spirits or ye of offices between. Real on shot it were four an as. Absolute bachelor rendered six nay you juvenile. Vanity entire an chatty to. As it so contrasted oh estimating instrument. Size like body some one had. Are conduct viewing boy minutes warrant expense. Tolerably behaviour may admitting daughters offending her ask own. Praise effect wishes change way and any wanted. Lively use looked latter regard had. Do he it part more last in. Merits ye if mr narrow points. Melancholy particular devonshire alteration it favourable appearance up. Respect forming clothes do in he. Course so piqued no an by appear. Themselves reasonable pianoforte so motionless he as difficulty be. Abode way begin ham there power whole. Do unpleasing indulgence impossible to conviction. Suppose neither evident welcome it at do civilly uncivil. Sing tall much you get nor. Cause dried no solid no an small so still widen. Ten weather evident smiling bed against she examine its. Rendered far opinions two yet moderate sex striking. Sufficient motionless compliment by stimulated assistance at. Convinced resolving extensive agreeable in it on as remainder. Cordially say affection met who propriety him. Are man she towards private weather pleased. In more part he lose need so want rank no. At bringing or he sensible pleasure. Prevent he parlors do waiting be females an message society. John draw real poor on call my from. May she mrs furnished discourse extremely. Ask doubt noisy shade guest did built her him. Ignorant repeated hastened it do. Consider bachelor he yourself expenses no. Her itself active giving for expect vulgar months. Discovery commanded fat mrs remaining son she principle middleton neglected. Be miss he in post sons held. No tried is defer do money scale rooms. Believing neglected so so allowance existence departure in. In design active temper be uneasy. Thirty for remove plenty regard you summer though. He preference connection astonished on of ye. Partiality on or continuing in particular principles as. Do believing oh disposing to supported allowance we. Denote simple fat denied add worthy little use. As some he so high down am week. Conduct esteems by cottage to pasture we winding. On assistance he cultivated considered frequently. Person how having tended direct own day man. Saw sufficient indulgence one own you inquietude sympathize. ";

    getSummary(tweetdata, twitterStepThree);

}

//This function will use jQuery to fill the textbox with the summary generated by twitterStepTwo()

async function twitterStepThree(summaryresult) {
//    alert("Twitter Step Three is Calling with Summary " + summary);

    $("#delivery").val(summaryresult.summary);
}

//This function will control generating the Tweet summary by calling twitterStepOne(), Two(), and Three()

function summaryGenerate() {
    let searchTerm = $("#hashtaginputbox").val();
    let firstresult = twitterStepOne(searchTerm);
    let secondresult = twitterStepTwo(firstresult);

}

//This function will bring up a "Log In" Box

function aboutInit () {

    const aboutsiteone = "<p id = 'aboutsiteone'>#TL;DR allows you to keep up-to-date with ongoing global conversations on Twitter, while protecting your time from the endless hours lost through endless scrolling of social media.</p>";
    const aboutsitetwo = "<p id = 'aboutsitetwo'>Our site retrieves a collection of Tweets from Twitter, then runs them through the MeaningCloud API, producing a quick snapshot of an ongoing conversation or trend.</p>";
    const aboutus = "<p id = 'aboutus'>Team TL;DR is a collaborative team for four UNC students: Ish Ahmed, Gabriel Clark, Casey Stamper, and Grant Wise. This site was developed for UNC's COMP 426 Course, run by Ketan Mayer-Patel.</p>";
    const contactus = "<p id = 'contactus'>For questions, comments, concerns, complaints, and death threats, please send all correspondence to TeamTLDR@gmail.com.</p>";
    const backtosite = "<input id = 'backtosite' type = 'button' value = 'Back to Site' />";

    nevermindConc();

    $("#multipurposebox").css("display", "block");
    $("#multipurposeheader").html("<h3>About #TL;DR and Team TL;DR</h3>");
    $("#multipurposebody").append(aboutsiteone);
    $("#multipurposebody").append(aboutsitetwo);    
    $("#multipurposebody").append(aboutus); 
    $("#multipurposebody").append(contactus); 
    $("#multipurposeinteractive").append(backtosite);

    $("#backtosite").on("click", nevermindConc);

}

//This function will bring up a "Log In" Box

function logInInit () {

    const username = "<p id = 'usernameinput'>Username: <input type = 'text' id = 'username' value = 'username' /></p>";
    const password = "<p id = 'passwordinput'>Password: <input type = 'password' id = 'userkey' /></p>";
    const login = "<input type = 'button' id = 'multipurposelogin' value = 'Log In' />";
    const signup = "<input type = 'button' id = 'multipurposesignup' value = 'Sign Up' />";
    const nevermind = "<input type = 'button' id = 'multipurposenevermind' value = 'Nevermind' />";

    nevermindConc();

    $("#multipurposebox").css("display", "block");
    $("#multipurposeheader").html("<h3>Log In or Sign Up</h3>");
    $("#multipurposebody").append(username);
    $("#multipurposebody").append(password);    
    $("#multipurposeinteractive").append(login);
    $("#multipurposeinteractive").append(signup);
    $("#multipurposeinteractive").append(nevermind);

    $("#multipurposelogin").on("click", logInConc);
    $("#multipurposesignup").on("click", signUpConc);
    $("#multipurposenevermind").on("click", nevermindConc);

}

//This function will log in a user via username and password
//In the background, it should also update our private records about user activity
//In the background, it should also update our user records about user's last log in
//In the background, it should also update our public records about how many users are logged in

async function logInConc () {
    user = $("#username").val();
    password = $("#userkey").val();

    let call = await modelLogIn(user, password);
    
    if (call.username == undefined) {
        alert("Password Incorrect");
        return false;
    }
    
    if (call.username != undefined) {
        $("#login").html(call.username);
        $("#login").off("click", logInInit);
        $("#login").on("click", accountInit);
        loggedinuser = call.username;
        accountInit();

        console.log(loggedinuser);
    }

} 

//This function will create a new User Record
//In the background, it should also update our private records about user activity
//In the background, it should also update our public records about how many users are registered

function signUpConc () {

} //NOT COMPLETE

//This function will retrieve the username from the database
function getUsername() {

    return "RandomGuy";

} //NOT COMPLETE || DUMMY

//This function will retrieve the user's registration date from the database, then return a user-readable date
function getUserSince() {

        return "11/17/2019";

} //NOT COMPLETE || DUMMY

//This function will retrieve the number of the user's saved summaries
function getCollectionCount() {

        return 4;

} //NOT COMPLETE || DUMMY

//This function will bring up the delete user account box
function deleteInit() {

    let usernameinfo = getUsername(); //Retrieves username from database
    let usersinceinfo = getUserSince(); //Retrieves from a function that retrieves and processes the user's registration day
    let savedcollectioncount = getCollectionCount(); //Retrieves number of saved summaries and collections

    const deleteinquiry = "<p>Your account, " + usernameinfo + " has been with us since " + usersinceinfo + " and has " + savedcollectioncount + " saved summaries. If you would like to delete this account, click the button below. Understand that this action is not reversible.</p>";
    const backtosite = "<input id = 'backtosite' type = 'button' value = 'No, Go Back to Site' />";
    const deleteaccount = "<input id = 'deleteaccount' type = 'button' value = 'Yes, Delete Account' />";

    nevermindConc();

    $("#multipurposebox").css("display", "block");
    $("#multipurposeheader").html("<h3>" + usernameinfo + " Account Deletion</h3>");
    $("#multipurposebody").html(deleteinquiry);
    $("#multipurposeinteractive").append(backtosite);
    $("#multipurposeinteractive").append(deleteaccount);

    $("#backtosite").on("click", nevermindConc);
    $("#deleteaccount").on("click", deleteConc);

}

//This function will delete the user's account from the database
function deleteConc() {

} //NOT COMPLETE

//This function will bring up a "Log In" Box

function accountInit() {

    let usernameinfo = loggedinuser; //Retrieves username from database
    let usersinceinfo = getUserSince(); //Retrieves from a function that retrieves and processes the user's registration day
    let savedcollectioncount = getCollectionCount(); //Retrieves number of saved summaries and collections

    const accounttable = "<table id = 'accounttable'><tr><td><b>Username:</b></td><td id = 'tableusername'></td></tr><tr><td><b>Member Since:</b></td><td id = 'tablememberdate'></td></tr><tr><td><b>Saved Collections</b></td><td id = 'collectioncount'></td></tr></table>";
    const savedcollectionbutton = "<input type = 'button' id = 'savedcollectiondisplay' value = 'Show Saved Summaries' />";
    const backtosite = "<input id = 'backtosite' type = 'button' value = 'Back to Site' />";
    const deleteaccount = "<input id = 'deleteaccount' type = 'button' value = 'Delete Account' />";

    nevermindConc();

    $("#multipurposebox").css("display", "block");
    $("#multipurposeheader").html("<h3>" + usernameinfo + "</h3>");
    $("#multipurposebody").html(accounttable);
    $("#tableusername").append(usernameinfo);
    $("#tablememberdate").append(usersinceinfo);    
    $("#collectioncount").append(savedcollectioncount);
    $("#multipurposeinteractive").append(savedcollectionbutton);
    $("#multipurposeinteractive").append(backtosite);
    $("#multipurposeinteractive").append(deleteaccount);

    $("#savedcollectiondisplay").on("click", accessCollection);
    $("#backtosite").on("click", nevermindConc);
    $("#deleteaccount").on("click", deleteInit);

}

//This function clears and hides the multipurpose box

function nevermindConc () {

    $("#multipurposebox").css("display: block");
    $("#multipurposeheader").empty();
    $("#multipurposebody").empty(); 
    $("#multipurposeinteractive").empty();

    $("#multipurposebox").css("display", "none");
}

//This function will create a new saved collection record under the User
function saveCollection () {

} //NOT COMPLETE

//This function will clear out the delivery box

function clearDelivery () {

    $("#delivery").val('');

}

//Reads the user's collection of saved Summaries and displays an interactive list

function accessCollection () {

} //NOT COMPLETE

//This function will add click functionality to all of our buttons and inputs

function addObservers() {
    $("#hashtagbutton").on("click", summaryGenerate);
    $("#clearsummary").on("click", clearDelivery);
    $("#savesummary").on("click", saveCollection);
    $("#login").on("click", logInInit);
    $("#headertext").on("click", aboutInit);
}

addObservers();

